// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotifyLocalStats.Server.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(SpotifyStatsContext))]
    [Migration("20260203081542_OnModelCreating")]
    partial class OnModelCreating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbumArtist", b =>
                {
                    b.Property<Guid>("AlbumsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlbumsId", "ArtistsId");

                    b.HasIndex("ArtistsId");

                    b.ToTable("AlbumArtist");
                });

            modelBuilder.Entity("AlbumTrack", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TracksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlbumId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("AlbumTrack");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStreakDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeFirstListened")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeLastListened")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestDrySpell")
                        .HasColumnType("int");

                    b.Property<DateTime>("LongestDrySpellEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LongestDrySpellStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreakDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LongestStreakEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LongestStreakStartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("MinsListened")
                        .HasColumnType("float");

                    b.Property<int>("MostTimesIn24Hours")
                        .HasColumnType("int");

                    b.Property<int>("MsListened")
                        .HasColumnType("int");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("TimesCompleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("TopListeningDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("UserId");

                    b.ToTable("AggregatedAlbums");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedArtist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlbumsListened")
                        .HasColumnType("int");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStreakDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeFirstListened")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeLastListened")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestDrySpell")
                        .HasColumnType("int");

                    b.Property<DateTime>("LongestDrySpellEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LongestDrySpellStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreakDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LongestStreakEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LongestStreakStartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("MinsListened")
                        .HasColumnType("float");

                    b.Property<int>("MostTimesIn24Hours")
                        .HasColumnType("int");

                    b.Property<int>("MsListened")
                        .HasColumnType("int");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TopListeningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UniqueTracksPlayed")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("UserId");

                    b.ToTable("AggregatedArtists");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStreakDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeFirstListened")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeLastListened")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestDrySpell")
                        .HasColumnType("int");

                    b.Property<DateTime>("LongestDrySpellEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LongestDrySpellStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreakDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LongestStreakEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LongestStreakStartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("MinsListened")
                        .HasColumnType("float");

                    b.Property<int>("MostTimesIn24Hours")
                        .HasColumnType("int");

                    b.Property<int>("MsListened")
                        .HasColumnType("int");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TopListeningDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId");

                    b.ToTable("AggregatedTracks");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AvaliableMarkets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CopyrightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealeaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDatePrecision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CopyrightId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBand")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimesPlayed")
                        .HasColumnType("int");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.CopyrightContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CopyrightContent");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.ExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Upc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TrackId");

                    b.ToTable("ExternalId");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("UserId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.ImportedTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudiobookChapterTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "audiobook_chapter_title");

                    b.Property<string>("AudiobookChapterUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "audiobook_chapter_uri");

                    b.Property<string>("AudiobookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "audiobook_title");

                    b.Property<string>("AudiobookUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "audiobook_uri");

                    b.Property<string>("ConnCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "conn_country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EpisodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "episode_name");

                    b.Property<string>("EpisodeShowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "episode_show_name");

                    b.Property<bool>("IncognitoMode")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "incognito_mode");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "offline");

                    b.Property<bool>("IsShuffle")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "shuffle");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "skipped");

                    b.Property<string>("MasterMetadataAlbumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "master_metadata_album_album_name");

                    b.Property<string>("MasterMetadataArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "master_metadata_album_artist_name");

                    b.Property<string>("MasterMetadataTrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "master_metadata_track_name");

                    b.Property<int>("MsPlayed")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "ms_played");

                    b.Property<DateTime>("OfflineTimestamp")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "offline_timestamp");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<string>("ReasonEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "reason_end");

                    b.Property<string>("ReasonStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "reason_start");

                    b.Property<string>("SpotifyEpisodeUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "spotify_episode_uri");

                    b.Property<string>("SpotifyTrackUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "spotify_track_uri");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "ts");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TimeStamp", "SpotifyTrackUri", "UserId" }, "IX_TsAndSpotifyUriAndUserId")
                        .IsUnique();

                    b.ToTable("ImportedTracks");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AvaliableMarkets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExplicit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSingle")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDatePrecision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyTrackId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyTrackUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Auth")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasImportedHistorical")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastTimeUsed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyHref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyPermissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayStat<SpotifyLocalStats.Server.Models.AggregatedAlbum>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.ToTable("AlbumTimeOfDaysStats");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayStat<SpotifyLocalStats.Server.Models.AggregatedArtist>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.ToTable("ArtistTimeOfDaysStats");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayStat<SpotifyLocalStats.Server.Models.AggregatedTrack>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.ToTable("TrackTimeOfDaysStats");
                });

            modelBuilder.Entity("AlbumArtist", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlbumTrack", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedAlbum", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedArtist", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedTrack", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Album", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.CopyrightContent", "Copyright")
                        .WithMany()
                        .HasForeignKey("CopyrightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Copyright");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Artist", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Track", null)
                        .WithMany("Artists")
                        .HasForeignKey("TrackId");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.ExternalId", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", null)
                        .WithMany("ExternalIds")
                        .HasForeignKey("AlbumId");

                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", null)
                        .WithMany("ExternalIds")
                        .HasForeignKey("ArtistId");

                    b.HasOne("SpotifyLocalStats.Server.Models.Track", null)
                        .WithMany("ExternalIds")
                        .HasForeignKey("TrackId");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Image", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", null)
                        .WithMany("Images")
                        .HasForeignKey("AlbumId");

                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", null)
                        .WithMany("Images")
                        .HasForeignKey("ArtistId");

                    b.HasOne("SpotifyLocalStats.Server.Models.User", null)
                        .WithMany("Images")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.ImportedTrack", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayStat<SpotifyLocalStats.Server.Models.AggregatedAlbum>", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.AggregatedAlbum", "Aggregate")
                        .WithMany("TimeOfDayStats")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregate");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayStat<SpotifyLocalStats.Server.Models.AggregatedArtist>", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.AggregatedArtist", "Aggregate")
                        .WithMany("TimeOfDayStats")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregate");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayStat<SpotifyLocalStats.Server.Models.AggregatedTrack>", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.AggregatedTrack", "Aggregate")
                        .WithMany("TimeOfDayStats")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregate");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedAlbum", b =>
                {
                    b.Navigation("TimeOfDayStats");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedArtist", b =>
                {
                    b.Navigation("TimeOfDayStats");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedTrack", b =>
                {
                    b.Navigation("TimeOfDayStats");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Album", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Artist", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Track", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("ExternalIds");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.User", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
