// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotifyLocalStats.Server.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(SpotifyStatsContext))]
    [Migration("20260304053044_Indexes")]
    partial class Indexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistTimeOfDayStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.ToTable("ArtistTimeOfDaysStats", (string)null);
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregateBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStreakDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTimeFirstListened")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeLastListened")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestDrySpell")
                        .HasColumnType("int");

                    b.Property<DateTime>("LongestDrySpellEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LongestDrySpellStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreakDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LongestStreakEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LongestStreakStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MostTimesIn24Hours")
                        .HasColumnType("int");

                    b.Property<long?>("MsListened")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TopListeningDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AggregateBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AvaliableMarkets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CopyrightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealeaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDatePrecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("TotalTracks")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CopyrightId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Genres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsBand")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimesPlayed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.CopyrightContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CopyrightContent");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.ExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Upc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("TrackId");

                    b.ToTable("ExternalId");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Width")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("UserId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.ImportedTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudiobookChapterTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "audiobook_chapter_title");

                    b.Property<string>("AudiobookChapterUri")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "audiobook_chapter_uri");

                    b.Property<string>("AudiobookTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "audiobook_title");

                    b.Property<string>("AudiobookUri")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "audiobook_uri");

                    b.Property<string>("ConnCountry")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "conn_country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EpisodeName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "episode_name");

                    b.Property<string>("EpisodeShowName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "episode_show_name");

                    b.Property<bool?>("IncognitoMode")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "incognito_mode");

                    b.Property<bool?>("IsOffline")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "offline");

                    b.Property<bool?>("IsShuffle")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "shuffle");

                    b.Property<bool?>("IsSkipped")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "skipped");

                    b.Property<string>("MasterMetadataAlbumName")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "master_metadata_album_album_name");

                    b.Property<string>("MasterMetadataArtistName")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "master_metadata_album_artist_name");

                    b.Property<string>("MasterMetadataTrackName")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "master_metadata_track_name");

                    b.Property<int?>("MsPlayed")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "ms_played");

                    b.Property<DateTime?>("OfflineTimestamp")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "offline_timestamp");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<string>("ReasonEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "reason_end");

                    b.Property<string>("ReasonStart")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "reason_start");

                    b.Property<string>("SpotifyEpisodeUri")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "spotify_episode_uri");

                    b.Property<string>("SpotifyTrackUri")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "spotify_track_uri");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "ts");

                    b.Property<Guid?>("UploadHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UploadHistoryId");

                    b.HasIndex(new[] { "UserId", "MasterMetadataAlbumName" }, "IX_ImportedTracks_UserId_AlbumName");

                    b.HasIndex(new[] { "UserId", "MasterMetadataArtistName" }, "IX_ImportedTracks_UserId_ArtistName");

                    b.HasIndex(new[] { "UserId", "MasterMetadataTrackName" }, "IX_ImportedTracks_UserId_TrackName");

                    b.HasIndex(new[] { "TimeStamp", "SpotifyTrackUri", "UserId" }, "IX_TsAndSpotifyUriAndUserId")
                        .IsUnique()
                        .HasFilter("[SpotifyTrackUri] IS NOT NULL");

                    b.ToTable("ImportedTracks");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AvaliableMarkets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscNumber")
                        .HasColumnType("int");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsExplicit")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSingle")
                        .HasColumnType("bit");

                    b.Property<int?>("MsPlayed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDatePrecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyTrackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyTrackUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Auth")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasImportedHistorical")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastTimeUsed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyHref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyPermissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Models.Jobs.ImportJobStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImportJobStatuses");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayConcretes.AlbumTimeOfDayStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.ToTable("AlbumTimeOfDaysStats", (string)null);
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayConcretes.TrackTimeOfDayStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.ToTable("TrackTimeOfDaysStats", (string)null);
                });

            modelBuilder.Entity("WebApi.Models.UploadHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UploadHistories");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedAlbum", b =>
                {
                    b.HasBaseType("SpotifyLocalStats.Server.Models.AggregateBase");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimesCompleted")
                        .HasColumnType("int");

                    b.HasIndex("AlbumId");

                    b.ToTable("AggregatedAlbums", (string)null);
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedArtist", b =>
                {
                    b.HasBaseType("SpotifyLocalStats.Server.Models.AggregateBase");

                    b.Property<int>("AlbumsListened")
                        .HasColumnType("int");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UniqueTracksPlayed")
                        .HasColumnType("int");

                    b.HasIndex("ArtistId");

                    b.ToTable("AggregatedArtists", (string)null);
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedTrack", b =>
                {
                    b.HasBaseType("SpotifyLocalStats.Server.Models.AggregateBase");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("TrackId");

                    b.ToTable("AggregatedTracks", (string)null);
                });

            modelBuilder.Entity("ArtistTimeOfDayStat", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.AggregatedArtist", "Aggregate")
                        .WithMany("TimeOfDayStats")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregate");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregateBase", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Album", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.CopyrightContent", "Copyright")
                        .WithMany()
                        .HasForeignKey("CopyrightId");

                    b.Navigation("Artist");

                    b.Navigation("Copyright");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.ExternalId", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", null)
                        .WithMany("ExternalIds")
                        .HasForeignKey("AlbumId");

                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", null)
                        .WithMany("ExternalIds")
                        .HasForeignKey("ArtistId");

                    b.HasOne("SpotifyLocalStats.Server.Models.Track", null)
                        .WithMany("ExternalIds")
                        .HasForeignKey("TrackId");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Image", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", null)
                        .WithMany("Images")
                        .HasForeignKey("AlbumId");

                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", null)
                        .WithMany("Images")
                        .HasForeignKey("ArtistId");

                    b.HasOne("SpotifyLocalStats.Server.Models.User", null)
                        .WithMany("Images")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.ImportedTrack", b =>
                {
                    b.HasOne("WebApi.Models.UploadHistory", "UploadHistory")
                        .WithMany()
                        .HasForeignKey("UploadHistoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SpotifyLocalStats.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Track", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayConcretes.AlbumTimeOfDayStat", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.AggregatedAlbum", "Aggregate")
                        .WithMany("TimeOfDayStats")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregate");
                });

            modelBuilder.Entity("WebApi.Models.TimeOfDayConcretes.TrackTimeOfDayStat", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.AggregatedTrack", "Aggregate")
                        .WithMany("TimeOfDayStats")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregate");
                });

            modelBuilder.Entity("WebApi.Models.UploadHistory", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedAlbum", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.AggregateBase", null)
                        .WithOne()
                        .HasForeignKey("SpotifyLocalStats.Server.Models.AggregatedAlbum", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedArtist", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.AggregateBase", null)
                        .WithOne()
                        .HasForeignKey("SpotifyLocalStats.Server.Models.AggregatedArtist", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedTrack", b =>
                {
                    b.HasOne("SpotifyLocalStats.Server.Models.AggregateBase", null)
                        .WithOne()
                        .HasForeignKey("SpotifyLocalStats.Server.Models.AggregatedTrack", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyLocalStats.Server.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Album", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("Images");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("ExternalIds");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.Track", b =>
                {
                    b.Navigation("ExternalIds");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.User", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedAlbum", b =>
                {
                    b.Navigation("TimeOfDayStats");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedArtist", b =>
                {
                    b.Navigation("TimeOfDayStats");
                });

            modelBuilder.Entity("SpotifyLocalStats.Server.Models.AggregatedTrack", b =>
                {
                    b.Navigation("TimeOfDayStats");
                });
#pragma warning restore 612, 618
        }
    }
}
