//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
  private http: {
    fetch(url: RequestInfo, init?: RequestInit): Promise<Response>;
  };
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(
    baseUrl?: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> },
  ) {
    this.http = http ? http : (window as any);
    this.baseUrl = baseUrl ?? "";
  }

  /**
   * @return OK
   */
  aggregateAlbum(
    userId: string,
    pageNumber: number,
  ): Promise<AggregateAlbumDto[]> {
    let url_ = this.baseUrl + "/api/AggregateAlbum/{userId}/{pageNumber}";
    if (userId === undefined || userId === null)
      throw new globalThis.Error("The parameter 'userId' must be defined.");
    url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
    if (pageNumber === undefined || pageNumber === null)
      throw new globalThis.Error("The parameter 'pageNumber' must be defined.");
    url_ = url_.replace("{pageNumber}", encodeURIComponent("" + pageNumber));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processAggregateAlbum(_response);
    });
  }

  protected processAggregateAlbum(
    response: Response,
  ): Promise<AggregateAlbumDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        if (Array.isArray(resultData200)) {
          result200 = [] as any;
          for (let item of resultData200)
            result200!.push(AggregateAlbumDto.fromJS(item));
        } else {
          result200 = null as any;
        }
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<AggregateAlbumDto[]>(null as any);
  }

  /**
   * @return OK
   */
  aggregateArtist(
    userId: string,
    pageNumber: number,
  ): Promise<AggregateArtistDto[]> {
    let url_ = this.baseUrl + "/api/AggregateArtist/{userId}/{pageNumber}";
    if (userId === undefined || userId === null)
      throw new globalThis.Error("The parameter 'userId' must be defined.");
    url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
    if (pageNumber === undefined || pageNumber === null)
      throw new globalThis.Error("The parameter 'pageNumber' must be defined.");
    url_ = url_.replace("{pageNumber}", encodeURIComponent("" + pageNumber));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processAggregateArtist(_response);
    });
  }

  protected processAggregateArtist(
    response: Response,
  ): Promise<AggregateArtistDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        if (Array.isArray(resultData200)) {
          result200 = [] as any;
          for (let item of resultData200)
            result200!.push(AggregateArtistDto.fromJS(item));
        } else {
          result200 = null as any;
        }
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<AggregateArtistDto[]>(null as any);
  }

  /**
   * @return OK
   */
  aggregateTrack(
    userId: string,
    pageNumber: number,
  ): Promise<AggregateTrackDto[]> {
    let url_ = this.baseUrl + "/api/AggregateTrack/{userId}/{pageNumber}";
    if (userId === undefined || userId === null)
      throw new globalThis.Error("The parameter 'userId' must be defined.");
    url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
    if (pageNumber === undefined || pageNumber === null)
      throw new globalThis.Error("The parameter 'pageNumber' must be defined.");
    url_ = url_.replace("{pageNumber}", encodeURIComponent("" + pageNumber));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processAggregateTrack(_response);
    });
  }

  protected processAggregateTrack(
    response: Response,
  ): Promise<AggregateTrackDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        if (Array.isArray(resultData200)) {
          result200 = [] as any;
          for (let item of resultData200)
            result200!.push(AggregateTrackDto.fromJS(item));
        } else {
          result200 = null as any;
        }
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<AggregateTrackDto[]>(null as any);
  }

  /**
   * @param userId (optional)
   * @param files (optional)
   * @return OK
   */
  importTracks(
    userId: string | undefined,
    files: FileParameter[] | undefined,
  ): Promise<ImportJobStatus[]> {
    let url_ = this.baseUrl + "/api/ImportTracks";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = new FormData();
    if (userId === null || userId === undefined)
      throw new globalThis.Error("The parameter 'userId' cannot be null.");
    else content_.append("userId", userId.toString());
    if (files === null || files === undefined)
      throw new globalThis.Error("The parameter 'files' cannot be null.");
    else
      files.forEach((item_) =>
        content_.append(
          "files",
          item_.data,
          item_.fileName ? item_.fileName : "files",
        ),
      );

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processImportTracks(_response);
    });
  }

  protected processImportTracks(
    response: Response,
  ): Promise<ImportJobStatus[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        if (Array.isArray(resultData200)) {
          result200 = [] as any;
          for (let item of resultData200)
            result200!.push(ImportJobStatus.fromJS(item));
        } else {
          result200 = null as any;
        }
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<ImportJobStatus[]>(null as any);
  }

  /**
   * @return OK
   */
  status(id: string): Promise<void> {
    let url_ = this.baseUrl + "/api/ImportTracks/{id}/status";
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {},
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processStatus(_response);
    });
  }

  protected processStatus(response: Response): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        return;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  stats(userId: string): Promise<UserSpotifyStatsDto> {
    let url_ = this.baseUrl + "/api/Stats/{userId}";
    if (userId === undefined || userId === null)
      throw new globalThis.Error("The parameter 'userId' must be defined.");
    url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processStats(_response);
    });
  }

  protected processStats(response: Response): Promise<UserSpotifyStatsDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = UserSpotifyStatsDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<UserSpotifyStatsDto>(null as any);
  }

  /**
   * @return OK
   */
  uploadHistory(userId: string): Promise<UploadHistoryResponseDto> {
    let url_ = this.baseUrl + "/api/UploadHistory/{userId}";
    if (userId === undefined || userId === null)
      throw new globalThis.Error("The parameter 'userId' must be defined.");
    url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processUploadHistory(_response);
    });
  }

  protected processUploadHistory(
    response: Response,
  ): Promise<UploadHistoryResponseDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = UploadHistoryResponseDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<UploadHistoryResponseDto>(null as any);
  }

  /**
   * @return OK
   */
  userGET(userId: string): Promise<UserDto> {
    let url_ = this.baseUrl + "/api/User/{userId}";
    if (userId === undefined || userId === null)
      throw new globalThis.Error("The parameter 'userId' must be defined.");
    url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processUserGET(_response);
    });
  }

  protected processUserGET(response: Response): Promise<UserDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = UserDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<UserDto>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  userPOST(body: CreateUserRequest | undefined): Promise<UserDto> {
    let url_ = this.baseUrl + "/api/User";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    };

    return this.http.fetch(url_, options_).then((_response: Response) => {
      return this.processUserPOST(_response);
    });
  }

  protected processUserPOST(response: Response): Promise<UserDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = UserDto.fromJS(resultData200);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers,
        );
      });
    }
    return Promise.resolve<UserDto>(null as any);
  }
}

export class AggregateAlbumDto implements IAggregateAlbumDto {
  name?: string | undefined;
  playCount?: number;
  minsListened?: number;
  topListeningDate?: Date;
  firstListened?: Date;
  lastListened?: Date;
  longestStreak?: number;
  longestStreakStart?: Date;
  longestStreakEnd?: Date;
  longestDrySpell?: number;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  mostTimesIn24Hours?: number;
  totalRecords?: number;
  timeOfDayStats?: AggregatedAlbumTimeOfDayStatDto[] | undefined;

  constructor(data?: IAggregateAlbumDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.name = _data["name"];
      this.playCount = _data["playCount"];
      this.minsListened = _data["minsListened"];
      this.topListeningDate = _data["topListeningDate"]
        ? new Date(_data["topListeningDate"].toString())
        : (undefined as any);
      this.firstListened = _data["firstListened"]
        ? new Date(_data["firstListened"].toString())
        : (undefined as any);
      this.lastListened = _data["lastListened"]
        ? new Date(_data["lastListened"].toString())
        : (undefined as any);
      this.longestStreak = _data["longestStreak"];
      this.longestStreakStart = _data["longestStreakStart"]
        ? new Date(_data["longestStreakStart"].toString())
        : (undefined as any);
      this.longestStreakEnd = _data["longestStreakEnd"]
        ? new Date(_data["longestStreakEnd"].toString())
        : (undefined as any);
      this.longestDrySpell = _data["longestDrySpell"];
      this.longestDrySpellStart = _data["longestDrySpellStart"]
        ? new Date(_data["longestDrySpellStart"].toString())
        : (undefined as any);
      this.longestDrySpellEnd = _data["longestDrySpellEnd"]
        ? new Date(_data["longestDrySpellEnd"].toString())
        : (undefined as any);
      this.mostTimesIn24Hours = _data["mostTimesIn24Hours"];
      this.totalRecords = _data["totalRecords"];
      if (Array.isArray(_data["timeOfDayStats"])) {
        this.timeOfDayStats = [] as any;
        for (let item of _data["timeOfDayStats"])
          this.timeOfDayStats!.push(
            AggregatedAlbumTimeOfDayStatDto.fromJS(item),
          );
      }
    }
  }

  static fromJS(data: any): AggregateAlbumDto {
    data = typeof data === "object" ? data : {};
    let result = new AggregateAlbumDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["name"] = this.name;
    data["playCount"] = this.playCount;
    data["minsListened"] = this.minsListened;
    data["topListeningDate"] = this.topListeningDate
      ? this.topListeningDate.toISOString()
      : (undefined as any);
    data["firstListened"] = this.firstListened
      ? this.firstListened.toISOString()
      : (undefined as any);
    data["lastListened"] = this.lastListened
      ? this.lastListened.toISOString()
      : (undefined as any);
    data["longestStreak"] = this.longestStreak;
    data["longestStreakStart"] = this.longestStreakStart
      ? this.longestStreakStart.toISOString()
      : (undefined as any);
    data["longestStreakEnd"] = this.longestStreakEnd
      ? this.longestStreakEnd.toISOString()
      : (undefined as any);
    data["longestDrySpell"] = this.longestDrySpell;
    data["longestDrySpellStart"] = this.longestDrySpellStart
      ? this.longestDrySpellStart.toISOString()
      : (undefined as any);
    data["longestDrySpellEnd"] = this.longestDrySpellEnd
      ? this.longestDrySpellEnd.toISOString()
      : (undefined as any);
    data["mostTimesIn24Hours"] = this.mostTimesIn24Hours;
    data["totalRecords"] = this.totalRecords;
    if (Array.isArray(this.timeOfDayStats)) {
      data["timeOfDayStats"] = [];
      for (let item of this.timeOfDayStats)
        data["timeOfDayStats"].push(item ? item.toJSON() : (undefined as any));
    }
    return data;
  }
}

export interface IAggregateAlbumDto {
  name?: string | undefined;
  playCount?: number;
  minsListened?: number;
  topListeningDate?: Date;
  firstListened?: Date;
  lastListened?: Date;
  longestStreak?: number;
  longestStreakStart?: Date;
  longestStreakEnd?: Date;
  longestDrySpell?: number;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  mostTimesIn24Hours?: number;
  totalRecords?: number;
  timeOfDayStats?: AggregatedAlbumTimeOfDayStatDto[] | undefined;
}

export class AggregateArtistDto implements IAggregateArtistDto {
  name?: string | undefined;
  playCount?: number;
  minsListened?: number;
  topListeningDate?: Date;
  firstListened?: Date;
  lastListened?: Date;
  longestStreak?: number;
  longestStreakStart?: Date;
  longestStreakEnd?: Date;
  longestDrySpell?: number;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  mostTimesIn24Hours?: number;
  totalRecords?: number;
  timeOfDayStats?: AggregatedArtistTimeOfDayStatDto[] | undefined;

  constructor(data?: IAggregateArtistDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.name = _data["name"];
      this.playCount = _data["playCount"];
      this.minsListened = _data["minsListened"];
      this.topListeningDate = _data["topListeningDate"]
        ? new Date(_data["topListeningDate"].toString())
        : (undefined as any);
      this.firstListened = _data["firstListened"]
        ? new Date(_data["firstListened"].toString())
        : (undefined as any);
      this.lastListened = _data["lastListened"]
        ? new Date(_data["lastListened"].toString())
        : (undefined as any);
      this.longestStreak = _data["longestStreak"];
      this.longestStreakStart = _data["longestStreakStart"]
        ? new Date(_data["longestStreakStart"].toString())
        : (undefined as any);
      this.longestStreakEnd = _data["longestStreakEnd"]
        ? new Date(_data["longestStreakEnd"].toString())
        : (undefined as any);
      this.longestDrySpell = _data["longestDrySpell"];
      this.longestDrySpellStart = _data["longestDrySpellStart"]
        ? new Date(_data["longestDrySpellStart"].toString())
        : (undefined as any);
      this.longestDrySpellEnd = _data["longestDrySpellEnd"]
        ? new Date(_data["longestDrySpellEnd"].toString())
        : (undefined as any);
      this.mostTimesIn24Hours = _data["mostTimesIn24Hours"];
      this.totalRecords = _data["totalRecords"];
      if (Array.isArray(_data["timeOfDayStats"])) {
        this.timeOfDayStats = [] as any;
        for (let item of _data["timeOfDayStats"])
          this.timeOfDayStats!.push(
            AggregatedArtistTimeOfDayStatDto.fromJS(item),
          );
      }
    }
  }

  static fromJS(data: any): AggregateArtistDto {
    data = typeof data === "object" ? data : {};
    let result = new AggregateArtistDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["name"] = this.name;
    data["playCount"] = this.playCount;
    data["minsListened"] = this.minsListened;
    data["topListeningDate"] = this.topListeningDate
      ? this.topListeningDate.toISOString()
      : (undefined as any);
    data["firstListened"] = this.firstListened
      ? this.firstListened.toISOString()
      : (undefined as any);
    data["lastListened"] = this.lastListened
      ? this.lastListened.toISOString()
      : (undefined as any);
    data["longestStreak"] = this.longestStreak;
    data["longestStreakStart"] = this.longestStreakStart
      ? this.longestStreakStart.toISOString()
      : (undefined as any);
    data["longestStreakEnd"] = this.longestStreakEnd
      ? this.longestStreakEnd.toISOString()
      : (undefined as any);
    data["longestDrySpell"] = this.longestDrySpell;
    data["longestDrySpellStart"] = this.longestDrySpellStart
      ? this.longestDrySpellStart.toISOString()
      : (undefined as any);
    data["longestDrySpellEnd"] = this.longestDrySpellEnd
      ? this.longestDrySpellEnd.toISOString()
      : (undefined as any);
    data["mostTimesIn24Hours"] = this.mostTimesIn24Hours;
    data["totalRecords"] = this.totalRecords;
    if (Array.isArray(this.timeOfDayStats)) {
      data["timeOfDayStats"] = [];
      for (let item of this.timeOfDayStats)
        data["timeOfDayStats"].push(item ? item.toJSON() : (undefined as any));
    }
    return data;
  }
}

export interface IAggregateArtistDto {
  name?: string | undefined;
  playCount?: number;
  minsListened?: number;
  topListeningDate?: Date;
  firstListened?: Date;
  lastListened?: Date;
  longestStreak?: number;
  longestStreakStart?: Date;
  longestStreakEnd?: Date;
  longestDrySpell?: number;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  mostTimesIn24Hours?: number;
  totalRecords?: number;
  timeOfDayStats?: AggregatedArtistTimeOfDayStatDto[] | undefined;
}

export class AggregateTrackDto implements IAggregateTrackDto {
  name?: string | undefined;
  playCount?: number;
  minsListened?: number;
  topListeningDate?: Date;
  firstListened?: Date;
  lastListened?: Date;
  longestStreak?: number;
  longestStreakStart?: Date;
  longestStreakEnd?: Date;
  longestDrySpell?: number;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  mostTimesIn24Hours?: number;
  totalRecords?: number;
  timeOfDayStats?: AggregatedTrackTimeOfDayStatDto[] | undefined;

  constructor(data?: IAggregateTrackDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.name = _data["name"];
      this.playCount = _data["playCount"];
      this.minsListened = _data["minsListened"];
      this.topListeningDate = _data["topListeningDate"]
        ? new Date(_data["topListeningDate"].toString())
        : (undefined as any);
      this.firstListened = _data["firstListened"]
        ? new Date(_data["firstListened"].toString())
        : (undefined as any);
      this.lastListened = _data["lastListened"]
        ? new Date(_data["lastListened"].toString())
        : (undefined as any);
      this.longestStreak = _data["longestStreak"];
      this.longestStreakStart = _data["longestStreakStart"]
        ? new Date(_data["longestStreakStart"].toString())
        : (undefined as any);
      this.longestStreakEnd = _data["longestStreakEnd"]
        ? new Date(_data["longestStreakEnd"].toString())
        : (undefined as any);
      this.longestDrySpell = _data["longestDrySpell"];
      this.longestDrySpellStart = _data["longestDrySpellStart"]
        ? new Date(_data["longestDrySpellStart"].toString())
        : (undefined as any);
      this.longestDrySpellEnd = _data["longestDrySpellEnd"]
        ? new Date(_data["longestDrySpellEnd"].toString())
        : (undefined as any);
      this.mostTimesIn24Hours = _data["mostTimesIn24Hours"];
      this.totalRecords = _data["totalRecords"];
      if (Array.isArray(_data["timeOfDayStats"])) {
        this.timeOfDayStats = [] as any;
        for (let item of _data["timeOfDayStats"])
          this.timeOfDayStats!.push(
            AggregatedTrackTimeOfDayStatDto.fromJS(item),
          );
      }
    }
  }

  static fromJS(data: any): AggregateTrackDto {
    data = typeof data === "object" ? data : {};
    let result = new AggregateTrackDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["name"] = this.name;
    data["playCount"] = this.playCount;
    data["minsListened"] = this.minsListened;
    data["topListeningDate"] = this.topListeningDate
      ? this.topListeningDate.toISOString()
      : (undefined as any);
    data["firstListened"] = this.firstListened
      ? this.firstListened.toISOString()
      : (undefined as any);
    data["lastListened"] = this.lastListened
      ? this.lastListened.toISOString()
      : (undefined as any);
    data["longestStreak"] = this.longestStreak;
    data["longestStreakStart"] = this.longestStreakStart
      ? this.longestStreakStart.toISOString()
      : (undefined as any);
    data["longestStreakEnd"] = this.longestStreakEnd
      ? this.longestStreakEnd.toISOString()
      : (undefined as any);
    data["longestDrySpell"] = this.longestDrySpell;
    data["longestDrySpellStart"] = this.longestDrySpellStart
      ? this.longestDrySpellStart.toISOString()
      : (undefined as any);
    data["longestDrySpellEnd"] = this.longestDrySpellEnd
      ? this.longestDrySpellEnd.toISOString()
      : (undefined as any);
    data["mostTimesIn24Hours"] = this.mostTimesIn24Hours;
    data["totalRecords"] = this.totalRecords;
    if (Array.isArray(this.timeOfDayStats)) {
      data["timeOfDayStats"] = [];
      for (let item of this.timeOfDayStats)
        data["timeOfDayStats"].push(item ? item.toJSON() : (undefined as any));
    }
    return data;
  }
}

export interface IAggregateTrackDto {
  name?: string | undefined;
  playCount?: number;
  minsListened?: number;
  topListeningDate?: Date;
  firstListened?: Date;
  lastListened?: Date;
  longestStreak?: number;
  longestStreakStart?: Date;
  longestStreakEnd?: Date;
  longestDrySpell?: number;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  mostTimesIn24Hours?: number;
  totalRecords?: number;
  timeOfDayStats?: AggregatedTrackTimeOfDayStatDto[] | undefined;
}

export class AggregatedAlbum implements IAggregatedAlbum {
  id?: string;
  createdAt?: Date;
  user?: User;
  userId?: string;
  playCount?: number;
  msListened?: number | undefined;
  readonly minsListened?: number;
  topListeningDate?: Date;
  dateTimeFirstListened?: Date;
  dateTimeLastListened?: Date;
  longestStreakDays?: number;
  longestStreakStartDate?: Date;
  longestStreakEndDate?: Date;
  currentStreakDays?: string | undefined;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  longestDrySpell?: number;
  mostTimesIn24Hours?: number;
  album?: Album;
  timeOfDayStats?: AlbumTimeOfDayStat[] | undefined;
  timesCompleted?: number;

  constructor(data?: IAggregatedAlbum) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.user = _data["user"]
        ? User.fromJS(_data["user"])
        : (undefined as any);
      this.userId = _data["userId"];
      this.playCount = _data["playCount"];
      this.msListened = _data["msListened"];
      (this as any).minsListened = _data["minsListened"];
      this.topListeningDate = _data["topListeningDate"]
        ? new Date(_data["topListeningDate"].toString())
        : (undefined as any);
      this.dateTimeFirstListened = _data["dateTimeFirstListened"]
        ? new Date(_data["dateTimeFirstListened"].toString())
        : (undefined as any);
      this.dateTimeLastListened = _data["dateTimeLastListened"]
        ? new Date(_data["dateTimeLastListened"].toString())
        : (undefined as any);
      this.longestStreakDays = _data["longestStreakDays"];
      this.longestStreakStartDate = _data["longestStreakStartDate"]
        ? new Date(_data["longestStreakStartDate"].toString())
        : (undefined as any);
      this.longestStreakEndDate = _data["longestStreakEndDate"]
        ? new Date(_data["longestStreakEndDate"].toString())
        : (undefined as any);
      this.currentStreakDays = _data["currentStreakDays"];
      this.longestDrySpellStart = _data["longestDrySpellStart"]
        ? new Date(_data["longestDrySpellStart"].toString())
        : (undefined as any);
      this.longestDrySpellEnd = _data["longestDrySpellEnd"]
        ? new Date(_data["longestDrySpellEnd"].toString())
        : (undefined as any);
      this.longestDrySpell = _data["longestDrySpell"];
      this.mostTimesIn24Hours = _data["mostTimesIn24Hours"];
      this.album = _data["album"]
        ? Album.fromJS(_data["album"])
        : (undefined as any);
      if (Array.isArray(_data["timeOfDayStats"])) {
        this.timeOfDayStats = [] as any;
        for (let item of _data["timeOfDayStats"])
          this.timeOfDayStats!.push(AlbumTimeOfDayStat.fromJS(item));
      }
      this.timesCompleted = _data["timesCompleted"];
    }
  }

  static fromJS(data: any): AggregatedAlbum {
    data = typeof data === "object" ? data : {};
    let result = new AggregatedAlbum();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["user"] = this.user ? this.user.toJSON() : (undefined as any);
    data["userId"] = this.userId;
    data["playCount"] = this.playCount;
    data["msListened"] = this.msListened;
    data["minsListened"] = this.minsListened;
    data["topListeningDate"] = this.topListeningDate
      ? this.topListeningDate.toISOString()
      : (undefined as any);
    data["dateTimeFirstListened"] = this.dateTimeFirstListened
      ? this.dateTimeFirstListened.toISOString()
      : (undefined as any);
    data["dateTimeLastListened"] = this.dateTimeLastListened
      ? this.dateTimeLastListened.toISOString()
      : (undefined as any);
    data["longestStreakDays"] = this.longestStreakDays;
    data["longestStreakStartDate"] = this.longestStreakStartDate
      ? this.longestStreakStartDate.toISOString()
      : (undefined as any);
    data["longestStreakEndDate"] = this.longestStreakEndDate
      ? this.longestStreakEndDate.toISOString()
      : (undefined as any);
    data["currentStreakDays"] = this.currentStreakDays;
    data["longestDrySpellStart"] = this.longestDrySpellStart
      ? this.longestDrySpellStart.toISOString()
      : (undefined as any);
    data["longestDrySpellEnd"] = this.longestDrySpellEnd
      ? this.longestDrySpellEnd.toISOString()
      : (undefined as any);
    data["longestDrySpell"] = this.longestDrySpell;
    data["mostTimesIn24Hours"] = this.mostTimesIn24Hours;
    data["album"] = this.album ? this.album.toJSON() : (undefined as any);
    if (Array.isArray(this.timeOfDayStats)) {
      data["timeOfDayStats"] = [];
      for (let item of this.timeOfDayStats)
        data["timeOfDayStats"].push(item ? item.toJSON() : (undefined as any));
    }
    data["timesCompleted"] = this.timesCompleted;
    return data;
  }
}

export interface IAggregatedAlbum {
  id?: string;
  createdAt?: Date;
  user?: User;
  userId?: string;
  playCount?: number;
  msListened?: number | undefined;
  minsListened?: number;
  topListeningDate?: Date;
  dateTimeFirstListened?: Date;
  dateTimeLastListened?: Date;
  longestStreakDays?: number;
  longestStreakStartDate?: Date;
  longestStreakEndDate?: Date;
  currentStreakDays?: string | undefined;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  longestDrySpell?: number;
  mostTimesIn24Hours?: number;
  album?: Album;
  timeOfDayStats?: AlbumTimeOfDayStat[] | undefined;
  timesCompleted?: number;
}

export class AggregatedAlbumTimeOfDayStatDto implements IAggregatedAlbumTimeOfDayStatDto {
  aggregate?: AggregatedAlbum;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  lastUpdatedAt?: Date;

  constructor(data?: IAggregatedAlbumTimeOfDayStatDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.aggregate = _data["aggregate"]
        ? AggregatedAlbum.fromJS(_data["aggregate"])
        : (undefined as any);
      this.aggregateId = _data["aggregateId"];
      this.timeOfDay = _data["timeOfDay"];
      this.playCount = _data["playCount"];
      this.lastUpdatedAt = _data["lastUpdatedAt"]
        ? new Date(_data["lastUpdatedAt"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): AggregatedAlbumTimeOfDayStatDto {
    data = typeof data === "object" ? data : {};
    let result = new AggregatedAlbumTimeOfDayStatDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["aggregate"] = this.aggregate
      ? this.aggregate.toJSON()
      : (undefined as any);
    data["aggregateId"] = this.aggregateId;
    data["timeOfDay"] = this.timeOfDay;
    data["playCount"] = this.playCount;
    data["lastUpdatedAt"] = this.lastUpdatedAt
      ? this.lastUpdatedAt.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface IAggregatedAlbumTimeOfDayStatDto {
  aggregate?: AggregatedAlbum;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  lastUpdatedAt?: Date;
}

export class AggregatedArtist implements IAggregatedArtist {
  id?: string;
  createdAt?: Date;
  user?: User;
  userId?: string;
  playCount?: number;
  msListened?: number | undefined;
  readonly minsListened?: number;
  topListeningDate?: Date;
  dateTimeFirstListened?: Date;
  dateTimeLastListened?: Date;
  longestStreakDays?: number;
  longestStreakStartDate?: Date;
  longestStreakEndDate?: Date;
  currentStreakDays?: string | undefined;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  longestDrySpell?: number;
  mostTimesIn24Hours?: number;
  artist?: Artist;
  timeOfDayStats?: ArtistTimeOfDayStat[] | undefined;
  uniqueTracksPlayed?: number;
  albumsListened?: number;

  constructor(data?: IAggregatedArtist) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.user = _data["user"]
        ? User.fromJS(_data["user"])
        : (undefined as any);
      this.userId = _data["userId"];
      this.playCount = _data["playCount"];
      this.msListened = _data["msListened"];
      (this as any).minsListened = _data["minsListened"];
      this.topListeningDate = _data["topListeningDate"]
        ? new Date(_data["topListeningDate"].toString())
        : (undefined as any);
      this.dateTimeFirstListened = _data["dateTimeFirstListened"]
        ? new Date(_data["dateTimeFirstListened"].toString())
        : (undefined as any);
      this.dateTimeLastListened = _data["dateTimeLastListened"]
        ? new Date(_data["dateTimeLastListened"].toString())
        : (undefined as any);
      this.longestStreakDays = _data["longestStreakDays"];
      this.longestStreakStartDate = _data["longestStreakStartDate"]
        ? new Date(_data["longestStreakStartDate"].toString())
        : (undefined as any);
      this.longestStreakEndDate = _data["longestStreakEndDate"]
        ? new Date(_data["longestStreakEndDate"].toString())
        : (undefined as any);
      this.currentStreakDays = _data["currentStreakDays"];
      this.longestDrySpellStart = _data["longestDrySpellStart"]
        ? new Date(_data["longestDrySpellStart"].toString())
        : (undefined as any);
      this.longestDrySpellEnd = _data["longestDrySpellEnd"]
        ? new Date(_data["longestDrySpellEnd"].toString())
        : (undefined as any);
      this.longestDrySpell = _data["longestDrySpell"];
      this.mostTimesIn24Hours = _data["mostTimesIn24Hours"];
      this.artist = _data["artist"]
        ? Artist.fromJS(_data["artist"])
        : (undefined as any);
      if (Array.isArray(_data["timeOfDayStats"])) {
        this.timeOfDayStats = [] as any;
        for (let item of _data["timeOfDayStats"])
          this.timeOfDayStats!.push(ArtistTimeOfDayStat.fromJS(item));
      }
      this.uniqueTracksPlayed = _data["uniqueTracksPlayed"];
      this.albumsListened = _data["albumsListened"];
    }
  }

  static fromJS(data: any): AggregatedArtist {
    data = typeof data === "object" ? data : {};
    let result = new AggregatedArtist();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["user"] = this.user ? this.user.toJSON() : (undefined as any);
    data["userId"] = this.userId;
    data["playCount"] = this.playCount;
    data["msListened"] = this.msListened;
    data["minsListened"] = this.minsListened;
    data["topListeningDate"] = this.topListeningDate
      ? this.topListeningDate.toISOString()
      : (undefined as any);
    data["dateTimeFirstListened"] = this.dateTimeFirstListened
      ? this.dateTimeFirstListened.toISOString()
      : (undefined as any);
    data["dateTimeLastListened"] = this.dateTimeLastListened
      ? this.dateTimeLastListened.toISOString()
      : (undefined as any);
    data["longestStreakDays"] = this.longestStreakDays;
    data["longestStreakStartDate"] = this.longestStreakStartDate
      ? this.longestStreakStartDate.toISOString()
      : (undefined as any);
    data["longestStreakEndDate"] = this.longestStreakEndDate
      ? this.longestStreakEndDate.toISOString()
      : (undefined as any);
    data["currentStreakDays"] = this.currentStreakDays;
    data["longestDrySpellStart"] = this.longestDrySpellStart
      ? this.longestDrySpellStart.toISOString()
      : (undefined as any);
    data["longestDrySpellEnd"] = this.longestDrySpellEnd
      ? this.longestDrySpellEnd.toISOString()
      : (undefined as any);
    data["longestDrySpell"] = this.longestDrySpell;
    data["mostTimesIn24Hours"] = this.mostTimesIn24Hours;
    data["artist"] = this.artist ? this.artist.toJSON() : (undefined as any);
    if (Array.isArray(this.timeOfDayStats)) {
      data["timeOfDayStats"] = [];
      for (let item of this.timeOfDayStats)
        data["timeOfDayStats"].push(item ? item.toJSON() : (undefined as any));
    }
    data["uniqueTracksPlayed"] = this.uniqueTracksPlayed;
    data["albumsListened"] = this.albumsListened;
    return data;
  }
}

export interface IAggregatedArtist {
  id?: string;
  createdAt?: Date;
  user?: User;
  userId?: string;
  playCount?: number;
  msListened?: number | undefined;
  minsListened?: number;
  topListeningDate?: Date;
  dateTimeFirstListened?: Date;
  dateTimeLastListened?: Date;
  longestStreakDays?: number;
  longestStreakStartDate?: Date;
  longestStreakEndDate?: Date;
  currentStreakDays?: string | undefined;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  longestDrySpell?: number;
  mostTimesIn24Hours?: number;
  artist?: Artist;
  timeOfDayStats?: ArtistTimeOfDayStat[] | undefined;
  uniqueTracksPlayed?: number;
  albumsListened?: number;
}

export class AggregatedArtistTimeOfDayStatDto implements IAggregatedArtistTimeOfDayStatDto {
  aggregate?: AggregatedArtist;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  lastUpdatedAt?: Date;

  constructor(data?: IAggregatedArtistTimeOfDayStatDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.aggregate = _data["aggregate"]
        ? AggregatedArtist.fromJS(_data["aggregate"])
        : (undefined as any);
      this.aggregateId = _data["aggregateId"];
      this.timeOfDay = _data["timeOfDay"];
      this.playCount = _data["playCount"];
      this.lastUpdatedAt = _data["lastUpdatedAt"]
        ? new Date(_data["lastUpdatedAt"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): AggregatedArtistTimeOfDayStatDto {
    data = typeof data === "object" ? data : {};
    let result = new AggregatedArtistTimeOfDayStatDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["aggregate"] = this.aggregate
      ? this.aggregate.toJSON()
      : (undefined as any);
    data["aggregateId"] = this.aggregateId;
    data["timeOfDay"] = this.timeOfDay;
    data["playCount"] = this.playCount;
    data["lastUpdatedAt"] = this.lastUpdatedAt
      ? this.lastUpdatedAt.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface IAggregatedArtistTimeOfDayStatDto {
  aggregate?: AggregatedArtist;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  lastUpdatedAt?: Date;
}

export class AggregatedTrack implements IAggregatedTrack {
  id?: string;
  createdAt?: Date;
  user?: User;
  userId?: string;
  playCount?: number;
  msListened?: number | undefined;
  readonly minsListened?: number;
  topListeningDate?: Date;
  dateTimeFirstListened?: Date;
  dateTimeLastListened?: Date;
  longestStreakDays?: number;
  longestStreakStartDate?: Date;
  longestStreakEndDate?: Date;
  currentStreakDays?: string | undefined;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  longestDrySpell?: number;
  mostTimesIn24Hours?: number;
  track?: Track;
  timeOfDayStats?: TrackTimeOfDayStat[] | undefined;

  constructor(data?: IAggregatedTrack) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.user = _data["user"]
        ? User.fromJS(_data["user"])
        : (undefined as any);
      this.userId = _data["userId"];
      this.playCount = _data["playCount"];
      this.msListened = _data["msListened"];
      (this as any).minsListened = _data["minsListened"];
      this.topListeningDate = _data["topListeningDate"]
        ? new Date(_data["topListeningDate"].toString())
        : (undefined as any);
      this.dateTimeFirstListened = _data["dateTimeFirstListened"]
        ? new Date(_data["dateTimeFirstListened"].toString())
        : (undefined as any);
      this.dateTimeLastListened = _data["dateTimeLastListened"]
        ? new Date(_data["dateTimeLastListened"].toString())
        : (undefined as any);
      this.longestStreakDays = _data["longestStreakDays"];
      this.longestStreakStartDate = _data["longestStreakStartDate"]
        ? new Date(_data["longestStreakStartDate"].toString())
        : (undefined as any);
      this.longestStreakEndDate = _data["longestStreakEndDate"]
        ? new Date(_data["longestStreakEndDate"].toString())
        : (undefined as any);
      this.currentStreakDays = _data["currentStreakDays"];
      this.longestDrySpellStart = _data["longestDrySpellStart"]
        ? new Date(_data["longestDrySpellStart"].toString())
        : (undefined as any);
      this.longestDrySpellEnd = _data["longestDrySpellEnd"]
        ? new Date(_data["longestDrySpellEnd"].toString())
        : (undefined as any);
      this.longestDrySpell = _data["longestDrySpell"];
      this.mostTimesIn24Hours = _data["mostTimesIn24Hours"];
      this.track = _data["track"]
        ? Track.fromJS(_data["track"])
        : (undefined as any);
      if (Array.isArray(_data["timeOfDayStats"])) {
        this.timeOfDayStats = [] as any;
        for (let item of _data["timeOfDayStats"])
          this.timeOfDayStats!.push(TrackTimeOfDayStat.fromJS(item));
      }
    }
  }

  static fromJS(data: any): AggregatedTrack {
    data = typeof data === "object" ? data : {};
    let result = new AggregatedTrack();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["user"] = this.user ? this.user.toJSON() : (undefined as any);
    data["userId"] = this.userId;
    data["playCount"] = this.playCount;
    data["msListened"] = this.msListened;
    data["minsListened"] = this.minsListened;
    data["topListeningDate"] = this.topListeningDate
      ? this.topListeningDate.toISOString()
      : (undefined as any);
    data["dateTimeFirstListened"] = this.dateTimeFirstListened
      ? this.dateTimeFirstListened.toISOString()
      : (undefined as any);
    data["dateTimeLastListened"] = this.dateTimeLastListened
      ? this.dateTimeLastListened.toISOString()
      : (undefined as any);
    data["longestStreakDays"] = this.longestStreakDays;
    data["longestStreakStartDate"] = this.longestStreakStartDate
      ? this.longestStreakStartDate.toISOString()
      : (undefined as any);
    data["longestStreakEndDate"] = this.longestStreakEndDate
      ? this.longestStreakEndDate.toISOString()
      : (undefined as any);
    data["currentStreakDays"] = this.currentStreakDays;
    data["longestDrySpellStart"] = this.longestDrySpellStart
      ? this.longestDrySpellStart.toISOString()
      : (undefined as any);
    data["longestDrySpellEnd"] = this.longestDrySpellEnd
      ? this.longestDrySpellEnd.toISOString()
      : (undefined as any);
    data["longestDrySpell"] = this.longestDrySpell;
    data["mostTimesIn24Hours"] = this.mostTimesIn24Hours;
    data["track"] = this.track ? this.track.toJSON() : (undefined as any);
    if (Array.isArray(this.timeOfDayStats)) {
      data["timeOfDayStats"] = [];
      for (let item of this.timeOfDayStats)
        data["timeOfDayStats"].push(item ? item.toJSON() : (undefined as any));
    }
    return data;
  }
}

export interface IAggregatedTrack {
  id?: string;
  createdAt?: Date;
  user?: User;
  userId?: string;
  playCount?: number;
  msListened?: number | undefined;
  minsListened?: number;
  topListeningDate?: Date;
  dateTimeFirstListened?: Date;
  dateTimeLastListened?: Date;
  longestStreakDays?: number;
  longestStreakStartDate?: Date;
  longestStreakEndDate?: Date;
  currentStreakDays?: string | undefined;
  longestDrySpellStart?: Date;
  longestDrySpellEnd?: Date;
  longestDrySpell?: number;
  mostTimesIn24Hours?: number;
  track?: Track;
  timeOfDayStats?: TrackTimeOfDayStat[] | undefined;
}

export class AggregatedTrackTimeOfDayStatDto implements IAggregatedTrackTimeOfDayStatDto {
  aggregate?: AggregatedTrack;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  lastUpdatedAt?: Date;

  constructor(data?: IAggregatedTrackTimeOfDayStatDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.aggregate = _data["aggregate"]
        ? AggregatedTrack.fromJS(_data["aggregate"])
        : (undefined as any);
      this.aggregateId = _data["aggregateId"];
      this.timeOfDay = _data["timeOfDay"];
      this.playCount = _data["playCount"];
      this.lastUpdatedAt = _data["lastUpdatedAt"]
        ? new Date(_data["lastUpdatedAt"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): AggregatedTrackTimeOfDayStatDto {
    data = typeof data === "object" ? data : {};
    let result = new AggregatedTrackTimeOfDayStatDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["aggregate"] = this.aggregate
      ? this.aggregate.toJSON()
      : (undefined as any);
    data["aggregateId"] = this.aggregateId;
    data["timeOfDay"] = this.timeOfDay;
    data["playCount"] = this.playCount;
    data["lastUpdatedAt"] = this.lastUpdatedAt
      ? this.lastUpdatedAt.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface IAggregatedTrackTimeOfDayStatDto {
  aggregate?: AggregatedTrack;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  lastUpdatedAt?: Date;
}

export class Album implements IAlbum {
  id?: string;
  createdAt?: Date;
  name?: string | undefined;
  type?: string | undefined;
  totalTracks?: number | undefined;
  artist?: Artist;
  avaliableMarkets?: string[] | undefined;
  href?: string | undefined;
  spotifyId?: string | undefined;
  spotifyUrl?: string | undefined;
  images?: Image[] | undefined;
  realeaseDate?: string | undefined;
  releaseDatePrecision?: string | undefined;
  tracks?: Track[] | undefined;
  copyrightId?: string | undefined;
  copyright?: CopyrightContent;
  externalIds?: ExternalId[] | undefined;
  label?: string | undefined;
  timesPlayed?: number | undefined;

  constructor(data?: IAlbum) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.name = _data["name"];
      this.type = _data["type"];
      this.totalTracks = _data["totalTracks"];
      this.artist = _data["artist"]
        ? Artist.fromJS(_data["artist"])
        : (undefined as any);
      if (Array.isArray(_data["avaliableMarkets"])) {
        this.avaliableMarkets = [] as any;
        for (let item of _data["avaliableMarkets"])
          this.avaliableMarkets!.push(item);
      }
      this.href = _data["href"];
      this.spotifyId = _data["spotifyId"];
      this.spotifyUrl = _data["spotifyUrl"];
      if (Array.isArray(_data["images"])) {
        this.images = [] as any;
        for (let item of _data["images"]) this.images!.push(Image.fromJS(item));
      }
      this.realeaseDate = _data["realeaseDate"];
      this.releaseDatePrecision = _data["releaseDatePrecision"];
      if (Array.isArray(_data["tracks"])) {
        this.tracks = [] as any;
        for (let item of _data["tracks"]) this.tracks!.push(Track.fromJS(item));
      }
      this.copyrightId = _data["copyrightId"];
      this.copyright = _data["copyright"]
        ? CopyrightContent.fromJS(_data["copyright"])
        : (undefined as any);
      if (Array.isArray(_data["externalIds"])) {
        this.externalIds = [] as any;
        for (let item of _data["externalIds"])
          this.externalIds!.push(ExternalId.fromJS(item));
      }
      this.label = _data["label"];
      this.timesPlayed = _data["timesPlayed"];
    }
  }

  static fromJS(data: any): Album {
    data = typeof data === "object" ? data : {};
    let result = new Album();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["name"] = this.name;
    data["type"] = this.type;
    data["totalTracks"] = this.totalTracks;
    data["artist"] = this.artist ? this.artist.toJSON() : (undefined as any);
    if (Array.isArray(this.avaliableMarkets)) {
      data["avaliableMarkets"] = [];
      for (let item of this.avaliableMarkets)
        data["avaliableMarkets"].push(item);
    }
    data["href"] = this.href;
    data["spotifyId"] = this.spotifyId;
    data["spotifyUrl"] = this.spotifyUrl;
    if (Array.isArray(this.images)) {
      data["images"] = [];
      for (let item of this.images)
        data["images"].push(item ? item.toJSON() : (undefined as any));
    }
    data["realeaseDate"] = this.realeaseDate;
    data["releaseDatePrecision"] = this.releaseDatePrecision;
    if (Array.isArray(this.tracks)) {
      data["tracks"] = [];
      for (let item of this.tracks)
        data["tracks"].push(item ? item.toJSON() : (undefined as any));
    }
    data["copyrightId"] = this.copyrightId;
    data["copyright"] = this.copyright
      ? this.copyright.toJSON()
      : (undefined as any);
    if (Array.isArray(this.externalIds)) {
      data["externalIds"] = [];
      for (let item of this.externalIds)
        data["externalIds"].push(item ? item.toJSON() : (undefined as any));
    }
    data["label"] = this.label;
    data["timesPlayed"] = this.timesPlayed;
    return data;
  }
}

export interface IAlbum {
  id?: string;
  createdAt?: Date;
  name?: string | undefined;
  type?: string | undefined;
  totalTracks?: number | undefined;
  artist?: Artist;
  avaliableMarkets?: string[] | undefined;
  href?: string | undefined;
  spotifyId?: string | undefined;
  spotifyUrl?: string | undefined;
  images?: Image[] | undefined;
  realeaseDate?: string | undefined;
  releaseDatePrecision?: string | undefined;
  tracks?: Track[] | undefined;
  copyrightId?: string | undefined;
  copyright?: CopyrightContent;
  externalIds?: ExternalId[] | undefined;
  label?: string | undefined;
  timesPlayed?: number | undefined;
}

export class AlbumTimeOfDayStat implements IAlbumTimeOfDayStat {
  readonly id?: string;
  aggregate?: AggregatedAlbum;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  createdAt?: Date;
  lastUpdatedAt?: Date;

  constructor(data?: IAlbumTimeOfDayStat) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      (this as any).id = _data["id"];
      this.aggregate = _data["aggregate"]
        ? AggregatedAlbum.fromJS(_data["aggregate"])
        : (undefined as any);
      this.aggregateId = _data["aggregateId"];
      this.timeOfDay = _data["timeOfDay"];
      this.playCount = _data["playCount"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.lastUpdatedAt = _data["lastUpdatedAt"]
        ? new Date(_data["lastUpdatedAt"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): AlbumTimeOfDayStat {
    data = typeof data === "object" ? data : {};
    let result = new AlbumTimeOfDayStat();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["aggregate"] = this.aggregate
      ? this.aggregate.toJSON()
      : (undefined as any);
    data["aggregateId"] = this.aggregateId;
    data["timeOfDay"] = this.timeOfDay;
    data["playCount"] = this.playCount;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["lastUpdatedAt"] = this.lastUpdatedAt
      ? this.lastUpdatedAt.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface IAlbumTimeOfDayStat {
  id?: string;
  aggregate?: AggregatedAlbum;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  createdAt?: Date;
  lastUpdatedAt?: Date;
}

export class Artist implements IArtist {
  id?: string;
  createdAt?: Date;
  name?: string | undefined;
  spotifyId?: string | undefined;
  spotifyUrl?: string | undefined;
  images?: Image[] | undefined;
  albums?: Album[] | undefined;
  href?: string | undefined;
  genres?: string | undefined;
  timesPlayed?: number | undefined;
  externalIds?: ExternalId[] | undefined;
  isBand?: boolean | undefined;
  dob?: Date;
  readonly age?: number | undefined;

  constructor(data?: IArtist) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.name = _data["name"];
      this.spotifyId = _data["spotifyId"];
      this.spotifyUrl = _data["spotifyUrl"];
      if (Array.isArray(_data["images"])) {
        this.images = [] as any;
        for (let item of _data["images"]) this.images!.push(Image.fromJS(item));
      }
      if (Array.isArray(_data["albums"])) {
        this.albums = [] as any;
        for (let item of _data["albums"]) this.albums!.push(Album.fromJS(item));
      }
      this.href = _data["href"];
      this.genres = _data["genres"];
      this.timesPlayed = _data["timesPlayed"];
      if (Array.isArray(_data["externalIds"])) {
        this.externalIds = [] as any;
        for (let item of _data["externalIds"])
          this.externalIds!.push(ExternalId.fromJS(item));
      }
      this.isBand = _data["isBand"];
      this.dob = _data["dob"]
        ? new Date(_data["dob"].toString())
        : (undefined as any);
      (this as any).age = _data["age"];
    }
  }

  static fromJS(data: any): Artist {
    data = typeof data === "object" ? data : {};
    let result = new Artist();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["name"] = this.name;
    data["spotifyId"] = this.spotifyId;
    data["spotifyUrl"] = this.spotifyUrl;
    if (Array.isArray(this.images)) {
      data["images"] = [];
      for (let item of this.images)
        data["images"].push(item ? item.toJSON() : (undefined as any));
    }
    if (Array.isArray(this.albums)) {
      data["albums"] = [];
      for (let item of this.albums)
        data["albums"].push(item ? item.toJSON() : (undefined as any));
    }
    data["href"] = this.href;
    data["genres"] = this.genres;
    data["timesPlayed"] = this.timesPlayed;
    if (Array.isArray(this.externalIds)) {
      data["externalIds"] = [];
      for (let item of this.externalIds)
        data["externalIds"].push(item ? item.toJSON() : (undefined as any));
    }
    data["isBand"] = this.isBand;
    data["dob"] = this.dob ? formatDate(this.dob) : (undefined as any);
    data["age"] = this.age;
    return data;
  }
}

export interface IArtist {
  id?: string;
  createdAt?: Date;
  name?: string | undefined;
  spotifyId?: string | undefined;
  spotifyUrl?: string | undefined;
  images?: Image[] | undefined;
  albums?: Album[] | undefined;
  href?: string | undefined;
  genres?: string | undefined;
  timesPlayed?: number | undefined;
  externalIds?: ExternalId[] | undefined;
  isBand?: boolean | undefined;
  dob?: Date;
  age?: number | undefined;
}

export class ArtistTimeOfDayStat implements IArtistTimeOfDayStat {
  readonly id?: string;
  aggregate?: AggregatedArtist;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  createdAt?: Date;
  lastUpdatedAt?: Date;

  constructor(data?: IArtistTimeOfDayStat) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      (this as any).id = _data["id"];
      this.aggregate = _data["aggregate"]
        ? AggregatedArtist.fromJS(_data["aggregate"])
        : (undefined as any);
      this.aggregateId = _data["aggregateId"];
      this.timeOfDay = _data["timeOfDay"];
      this.playCount = _data["playCount"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.lastUpdatedAt = _data["lastUpdatedAt"]
        ? new Date(_data["lastUpdatedAt"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): ArtistTimeOfDayStat {
    data = typeof data === "object" ? data : {};
    let result = new ArtistTimeOfDayStat();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["aggregate"] = this.aggregate
      ? this.aggregate.toJSON()
      : (undefined as any);
    data["aggregateId"] = this.aggregateId;
    data["timeOfDay"] = this.timeOfDay;
    data["playCount"] = this.playCount;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["lastUpdatedAt"] = this.lastUpdatedAt
      ? this.lastUpdatedAt.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface IArtistTimeOfDayStat {
  id?: string;
  aggregate?: AggregatedArtist;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  createdAt?: Date;
  lastUpdatedAt?: Date;
}

export class CopyrightContent implements ICopyrightContent {
  id?: string;
  createdAt?: Date;
  text?: string | undefined;
  type?: string | undefined;

  constructor(data?: ICopyrightContent) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.text = _data["text"];
      this.type = _data["type"];
    }
  }

  static fromJS(data: any): CopyrightContent {
    data = typeof data === "object" ? data : {};
    let result = new CopyrightContent();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["text"] = this.text;
    data["type"] = this.type;
    return data;
  }
}

export interface ICopyrightContent {
  id?: string;
  createdAt?: Date;
  text?: string | undefined;
  type?: string | undefined;
}

export class CreateUserRequest implements ICreateUserRequest {
  userName!: string;
  firstName!: string;

  constructor(data?: ICreateUserRequest) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.userName = _data["userName"];
      this.firstName = _data["firstName"];
    }
  }

  static fromJS(data: any): CreateUserRequest {
    data = typeof data === "object" ? data : {};
    let result = new CreateUserRequest();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["userName"] = this.userName;
    data["firstName"] = this.firstName;
    return data;
  }
}

export interface ICreateUserRequest {
  userName: string;
  firstName: string;
}

export class ExternalId implements IExternalId {
  id?: string;
  createdAt?: Date;
  isrc?: string | undefined;
  ean?: string | undefined;
  upc?: string | undefined;

  constructor(data?: IExternalId) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.isrc = _data["isrc"];
      this.ean = _data["ean"];
      this.upc = _data["upc"];
    }
  }

  static fromJS(data: any): ExternalId {
    data = typeof data === "object" ? data : {};
    let result = new ExternalId();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["isrc"] = this.isrc;
    data["ean"] = this.ean;
    data["upc"] = this.upc;
    return data;
  }
}

export interface IExternalId {
  id?: string;
  createdAt?: Date;
  isrc?: string | undefined;
  ean?: string | undefined;
  upc?: string | undefined;
}

export class Image implements IImage {
  id?: string;
  createdAt?: Date;
  url?: string | undefined;
  height?: string | undefined;
  width?: string | undefined;

  constructor(data?: IImage) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.url = _data["url"];
      this.height = _data["height"];
      this.width = _data["width"];
    }
  }

  static fromJS(data: any): Image {
    data = typeof data === "object" ? data : {};
    let result = new Image();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["url"] = this.url;
    data["height"] = this.height;
    data["width"] = this.width;
    return data;
  }
}

export interface IImage {
  id?: string;
  createdAt?: Date;
  url?: string | undefined;
  height?: string | undefined;
  width?: string | undefined;
}

export class ImportJobStatus implements IImportJobStatus {
  id?: string;
  status?: string;
  progressPercent?: number;
  errorMessage?: string | undefined;
  createdAt?: Date;
  completedAt?: Date | undefined;

  constructor(data?: IImportJobStatus) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.status = _data["status"];
      this.progressPercent = _data["progressPercent"];
      this.errorMessage = _data["errorMessage"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.completedAt = _data["completedAt"]
        ? new Date(_data["completedAt"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): ImportJobStatus {
    data = typeof data === "object" ? data : {};
    let result = new ImportJobStatus();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["status"] = this.status;
    data["progressPercent"] = this.progressPercent;
    data["errorMessage"] = this.errorMessage;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["completedAt"] = this.completedAt
      ? this.completedAt.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface IImportJobStatus {
  id?: string;
  status?: string;
  progressPercent?: number;
  errorMessage?: string | undefined;
  createdAt?: Date;
  completedAt?: Date | undefined;
}

export class Track implements ITrack {
  id?: string;
  createdAt?: Date;
  name?: string | undefined;
  album?: Album;
  artist?: Artist;
  spotifyTrackUri?: string | undefined;
  msPlayed?: number | undefined;
  isSingle?: boolean | undefined;
  isExplicit?: boolean | undefined;
  spotifyTrackId?: string | undefined;
  trackNumber?: number | undefined;
  releaseDate?: string | undefined;
  releaseDatePrecision?: string | undefined;
  discNumber?: number | undefined;
  previewUrl?: string | undefined;
  avaliableMarkets?: string[] | undefined;
  href?: string | undefined;
  externalIds?: ExternalId[] | undefined;
  timesPlayed?: number | undefined;

  constructor(data?: ITrack) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.name = _data["name"];
      this.album = _data["album"]
        ? Album.fromJS(_data["album"])
        : (undefined as any);
      this.artist = _data["artist"]
        ? Artist.fromJS(_data["artist"])
        : (undefined as any);
      this.spotifyTrackUri = _data["spotifyTrackUri"];
      this.msPlayed = _data["msPlayed"];
      this.isSingle = _data["isSingle"];
      this.isExplicit = _data["isExplicit"];
      this.spotifyTrackId = _data["spotifyTrackId"];
      this.trackNumber = _data["trackNumber"];
      this.releaseDate = _data["releaseDate"];
      this.releaseDatePrecision = _data["releaseDatePrecision"];
      this.discNumber = _data["discNumber"];
      this.previewUrl = _data["previewUrl"];
      if (Array.isArray(_data["avaliableMarkets"])) {
        this.avaliableMarkets = [] as any;
        for (let item of _data["avaliableMarkets"])
          this.avaliableMarkets!.push(item);
      }
      this.href = _data["href"];
      if (Array.isArray(_data["externalIds"])) {
        this.externalIds = [] as any;
        for (let item of _data["externalIds"])
          this.externalIds!.push(ExternalId.fromJS(item));
      }
      this.timesPlayed = _data["timesPlayed"];
    }
  }

  static fromJS(data: any): Track {
    data = typeof data === "object" ? data : {};
    let result = new Track();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["name"] = this.name;
    data["album"] = this.album ? this.album.toJSON() : (undefined as any);
    data["artist"] = this.artist ? this.artist.toJSON() : (undefined as any);
    data["spotifyTrackUri"] = this.spotifyTrackUri;
    data["msPlayed"] = this.msPlayed;
    data["isSingle"] = this.isSingle;
    data["isExplicit"] = this.isExplicit;
    data["spotifyTrackId"] = this.spotifyTrackId;
    data["trackNumber"] = this.trackNumber;
    data["releaseDate"] = this.releaseDate;
    data["releaseDatePrecision"] = this.releaseDatePrecision;
    data["discNumber"] = this.discNumber;
    data["previewUrl"] = this.previewUrl;
    if (Array.isArray(this.avaliableMarkets)) {
      data["avaliableMarkets"] = [];
      for (let item of this.avaliableMarkets)
        data["avaliableMarkets"].push(item);
    }
    data["href"] = this.href;
    if (Array.isArray(this.externalIds)) {
      data["externalIds"] = [];
      for (let item of this.externalIds)
        data["externalIds"].push(item ? item.toJSON() : (undefined as any));
    }
    data["timesPlayed"] = this.timesPlayed;
    return data;
  }
}

export interface ITrack {
  id?: string;
  createdAt?: Date;
  name?: string | undefined;
  album?: Album;
  artist?: Artist;
  spotifyTrackUri?: string | undefined;
  msPlayed?: number | undefined;
  isSingle?: boolean | undefined;
  isExplicit?: boolean | undefined;
  spotifyTrackId?: string | undefined;
  trackNumber?: number | undefined;
  releaseDate?: string | undefined;
  releaseDatePrecision?: string | undefined;
  discNumber?: number | undefined;
  previewUrl?: string | undefined;
  avaliableMarkets?: string[] | undefined;
  href?: string | undefined;
  externalIds?: ExternalId[] | undefined;
  timesPlayed?: number | undefined;
}

export class TrackTimeOfDayStat implements ITrackTimeOfDayStat {
  readonly id?: string;
  aggregate?: AggregatedTrack;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  createdAt?: Date;
  lastUpdatedAt?: Date;

  constructor(data?: ITrackTimeOfDayStat) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      (this as any).id = _data["id"];
      this.aggregate = _data["aggregate"]
        ? AggregatedTrack.fromJS(_data["aggregate"])
        : (undefined as any);
      this.aggregateId = _data["aggregateId"];
      this.timeOfDay = _data["timeOfDay"];
      this.playCount = _data["playCount"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.lastUpdatedAt = _data["lastUpdatedAt"]
        ? new Date(_data["lastUpdatedAt"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): TrackTimeOfDayStat {
    data = typeof data === "object" ? data : {};
    let result = new TrackTimeOfDayStat();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["aggregate"] = this.aggregate
      ? this.aggregate.toJSON()
      : (undefined as any);
    data["aggregateId"] = this.aggregateId;
    data["timeOfDay"] = this.timeOfDay;
    data["playCount"] = this.playCount;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["lastUpdatedAt"] = this.lastUpdatedAt
      ? this.lastUpdatedAt.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface ITrackTimeOfDayStat {
  id?: string;
  aggregate?: AggregatedTrack;
  aggregateId?: string;
  timeOfDay?: number;
  playCount?: number;
  createdAt?: Date;
  lastUpdatedAt?: Date;
}

export class UploadHistoryResponseDto implements IUploadHistoryResponseDto {
  fileName?: string | undefined;
  importedTrackCount?: number;
  createdAt?: Date;
  id?: string;

  constructor(data?: IUploadHistoryResponseDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.fileName = _data["fileName"];
      this.importedTrackCount = _data["importedTrackCount"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.id = _data["id"];
    }
  }

  static fromJS(data: any): UploadHistoryResponseDto {
    data = typeof data === "object" ? data : {};
    let result = new UploadHistoryResponseDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["fileName"] = this.fileName;
    data["importedTrackCount"] = this.importedTrackCount;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["id"] = this.id;
    return data;
  }
}

export interface IUploadHistoryResponseDto {
  fileName?: string | undefined;
  importedTrackCount?: number;
  createdAt?: Date;
  id?: string;
}

export class User implements IUser {
  id?: string;
  createdAt?: Date;
  lastUpdatedAt?: Date;
  lastTimeUsed?: Date;
  email?: string | undefined;
  userName?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  country?: string | undefined;
  phone?: string | undefined;
  auth?: boolean | undefined;
  spotifyPermissions?: string | undefined;
  spotifyId?: string | undefined;
  spotifyUri?: string | undefined;
  spotifyDisplayName?: string | undefined;
  spotifyHref?: string | undefined;
  images?: Image[] | undefined;
  isPremium?: boolean | undefined;
  hasImportedHistorical!: boolean;

  constructor(data?: IUser) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.createdAt = _data["createdAt"]
        ? new Date(_data["createdAt"].toString())
        : (undefined as any);
      this.lastUpdatedAt = _data["lastUpdatedAt"]
        ? new Date(_data["lastUpdatedAt"].toString())
        : (undefined as any);
      this.lastTimeUsed = _data["lastTimeUsed"]
        ? new Date(_data["lastTimeUsed"].toString())
        : (undefined as any);
      this.email = _data["email"];
      this.userName = _data["userName"];
      this.firstName = _data["firstName"];
      this.lastName = _data["lastName"];
      this.country = _data["country"];
      this.phone = _data["phone"];
      this.auth = _data["auth"];
      this.spotifyPermissions = _data["spotifyPermissions"];
      this.spotifyId = _data["spotifyId"];
      this.spotifyUri = _data["spotifyUri"];
      this.spotifyDisplayName = _data["spotifyDisplayName"];
      this.spotifyHref = _data["spotifyHref"];
      if (Array.isArray(_data["images"])) {
        this.images = [] as any;
        for (let item of _data["images"]) this.images!.push(Image.fromJS(item));
      }
      this.isPremium = _data["isPremium"];
      this.hasImportedHistorical = _data["hasImportedHistorical"];
    }
  }

  static fromJS(data: any): User {
    data = typeof data === "object" ? data : {};
    let result = new User();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["createdAt"] = this.createdAt
      ? this.createdAt.toISOString()
      : (undefined as any);
    data["lastUpdatedAt"] = this.lastUpdatedAt
      ? this.lastUpdatedAt.toISOString()
      : (undefined as any);
    data["lastTimeUsed"] = this.lastTimeUsed
      ? this.lastTimeUsed.toISOString()
      : (undefined as any);
    data["email"] = this.email;
    data["userName"] = this.userName;
    data["firstName"] = this.firstName;
    data["lastName"] = this.lastName;
    data["country"] = this.country;
    data["phone"] = this.phone;
    data["auth"] = this.auth;
    data["spotifyPermissions"] = this.spotifyPermissions;
    data["spotifyId"] = this.spotifyId;
    data["spotifyUri"] = this.spotifyUri;
    data["spotifyDisplayName"] = this.spotifyDisplayName;
    data["spotifyHref"] = this.spotifyHref;
    if (Array.isArray(this.images)) {
      data["images"] = [];
      for (let item of this.images)
        data["images"].push(item ? item.toJSON() : (undefined as any));
    }
    data["isPremium"] = this.isPremium;
    data["hasImportedHistorical"] = this.hasImportedHistorical;
    return data;
  }
}

export interface IUser {
  id?: string;
  createdAt?: Date;
  lastUpdatedAt?: Date;
  lastTimeUsed?: Date;
  email?: string | undefined;
  userName?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  country?: string | undefined;
  phone?: string | undefined;
  auth?: boolean | undefined;
  spotifyPermissions?: string | undefined;
  spotifyId?: string | undefined;
  spotifyUri?: string | undefined;
  spotifyDisplayName?: string | undefined;
  spotifyHref?: string | undefined;
  images?: Image[] | undefined;
  isPremium?: boolean | undefined;
  hasImportedHistorical: boolean;
}

export class UserDto implements IUserDto {
  userName?: string | undefined;
  id?: string;

  constructor(data?: IUserDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.userName = _data["userName"];
      this.id = _data["id"];
    }
  }

  static fromJS(data: any): UserDto {
    data = typeof data === "object" ? data : {};
    let result = new UserDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["userName"] = this.userName;
    data["id"] = this.id;
    return data;
  }
}

export interface IUserDto {
  userName?: string | undefined;
  id?: string;
}

export class UserSpotifyStatsDto implements IUserSpotifyStatsDto {
  trackCount?: number;
  artistCount?: number;
  albumCount?: number;

  constructor(data?: IUserSpotifyStatsDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.trackCount = _data["trackCount"];
      this.artistCount = _data["artistCount"];
      this.albumCount = _data["albumCount"];
    }
  }

  static fromJS(data: any): UserSpotifyStatsDto {
    data = typeof data === "object" ? data : {};
    let result = new UserSpotifyStatsDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["trackCount"] = this.trackCount;
    data["artistCount"] = this.artistCount;
    data["albumCount"] = this.albumCount;
    return data;
  }
}

export interface IUserSpotifyStatsDto {
  trackCount?: number;
  artistCount?: number;
  albumCount?: number;
}

function formatDate(d: Date) {
  return (
    d.getFullYear() +
    "-" +
    (d.getMonth() < 9 ? "0" + (d.getMonth() + 1) : d.getMonth() + 1) +
    "-" +
    (d.getDate() < 10 ? "0" + d.getDate() : d.getDate())
  );
}

export interface FileParameter {
  data: any;
  fileName: string;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result;
  else throw new ApiException(message, status, response, headers, null);
}
